name: "Release-Builder"
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags-ignore:
      - "v*"
    paths-ignore:
      - .github/workflows/*
      - README.md
      - assets/*
env:
  PYTHON_VER: "3.10"
jobs:
  deps:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Build"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Install Plugin dependencies
        if: steps.plugin-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r ./requirements.txt
      - name: Install Build dependencies
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: |
          pip install -r ./requirements-dev.txt
      - name: Build
        run: |
          python -m nuitka run.py --assume-yes-for-downloads --standalone --windows-icon-from-ico=icon.png --include-data-file=plugin.json=. --include-data-file=LICENSE=. --include-data-file=SettingsTemplate.yaml=.
      - name: Get Plugin's version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "plugin.json"
          prop_path: "Version"
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          directory: "./run.dist"
          filename: "${{github.event.repository.name}}.zip"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: "./run.dist/${{github.event.repository.name}}.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
