name: "Release-Builder"
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags-ignore:
      - "v*"
    paths-ignore:
      - .github/workflows/*
      - README.md
      - assets/*
env:
  PYTHON_VER: 3.8
jobs:
  deps:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Build"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r ./requirements.txt -t ./lib
          pip install -r ./requirements-dev.txt
      - name: Build
        run: |
          python -m nuitka run.py --standalone --onefile
      - name: Move files to staging
        run: |
          mkdir -p staging
          mv run.exe staging
          mv plugin.json staging
          mv icon.png staging
      - name: Get Plugin's version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "plugin.json"
          prop_path: "Version"
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          directory: "./staging"
          filename: "${{github.event.repository.name}}.zip"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: "./${{github.event.repository.name}}.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
